insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Alys', 'Kessiah', 'McAw', 'Samson', '62647 Harper Terrace', '2262979662');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Fayth', 'Carin', 'Alyutin', 'Neeves', '25427 Ludington Avenue', '6149570172');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Corinna', 'Chloris', 'Coupe', 'Jeanneau', '6316 Sunnyside Junction', '2689346843');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Leone', 'Sonny', 'Hankins', 'Durie', '1232 Fieldstone Plaza', '5109089757');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Lucienne', 'Gui', 'Adamini', 'Ghelarducci', '1 Utah Road', '2978288987');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Marlo', 'Izzy', 'Edmeades', 'Cullrford', '208 Bay Trail', '3681681649');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Madel', 'Ikey', 'Hise', 'Wegman', '5548 Delaware Avenue', '8905663504');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Skipper', 'Yoshi', 'Loghan', 'Garrold', '834 Melvin Junction', '7433080313');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Claretta', 'Vanya', 'Darlaston', 'Fearnill', '4772 2nd Circle', '3891993520');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Zorah', 'Berry', 'Bradnick', 'Keogh', '925 Del Mar Center', '5268782050');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Dore', 'Susi', 'Scally', 'Celes', '24746 Blaine Avenue', '9932466287');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Stanly', 'Ann-marie', 'Gathercoal', 'Sillick', '61826 Marquette Point', '9184760968');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Inez', 'Cleavland', 'Terris', 'Rawdales', '4240 Green Way', '8844864473');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Emmott', 'Curcio', 'Robbings', 'Etchingham', '67267 Longview Hill', '2479744656');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Marlyn', 'Germaine', 'Pryell', 'Latek', '161 Forest Run Pass', '8078872832');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Gordy', 'Zollie', 'Lugsdin', 'Genge', '94 Twin Pines Lane', '7983550846');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Alistair', 'Daisy', 'Simeone', 'Penswick', '150 Continental Drive', '9813405047');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Gabriella', 'Sandye', 'Eidler', 'Sprulls', '141 Mccormick Junction', '7517840391');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Mikaela', 'Marthena', 'Emmins', 'Fretter', '0465 Blackbird Drive', '4171370367');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Flss', 'Ignace', 'Arthur', 'McGourty', '43 Packers Pass', '2186498314');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Rufus', 'Catherina', 'Mounsey', 'Whittam', '78631 Hovde Pass', '8879779053');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Adelaide', 'Cristabel', 'Thurlow', 'Basley', '709 Ryan Junction', '1203439205');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Willdon', 'Yuri', 'Farlamb', 'Pidgin', '951 Manitowish Drive', '4867281670');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Egan', 'Jamey', 'Grabeham', 'Northcott', '04755 Burning Wood Lane', '9267091295');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Rickie', 'Delmar', 'Withur', 'Le Marchand', '47 Haas Plaza', '1817857882');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Mathilda', 'Jacquelyn', 'Lavington', 'Tolcher', '3871 Eggendart Way', '3289108951');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Shermie', 'Veronica', 'Scotchmoor', 'Ormrod', '58997 Sunfield Plaza', '3253123278');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Christian', 'Loy', 'Cardozo', 'Aim', '701 Delladonna Road', '7469319180');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Chandra', 'Phillipe', 'Rickersy', 'Bodd', '526 Prairie Rose Plaza', '2239988571');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Susanna', 'Skip', 'Gile', 'Braikenridge', '27016 Homewood Center', '1568951390');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Elbert', 'Alfi', 'McQuorkell', 'Regan', '8925 Darwin Circle', '7586569369');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Petronia', 'Rivi', 'Radnedge', 'Whitchurch', '62982 Oakridge Crossing', '1606125268');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Lib', 'Vernen', 'Grinvalds', 'Pulteneye', '259 Village Green Court', '6297797339');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Ellynn', 'Massimo', 'Hardisty', 'Craw', '30394 Goodland Plaza', '1969387426');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Martina', 'Ev', 'Verey', 'Guly', '7 Chinook Circle', '1729303618');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Jinny', 'Pedro', 'Hennington', 'Chucks', '73418 Parkside Park', '7829100581');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Athene', 'Mikol', 'Teacy', 'Matthius', '61077 Arapahoe Circle', '5731986555');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Carney', 'Kamilah', 'Gery', 'Bertlin', '290 Ridge Oak Terrace', '2497564185');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Filberto', 'Mabelle', 'Corter', 'Klimuk', '67754 Center Avenue', '8252129427');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Adelaide', 'Berny', 'Pagan', 'Fasham', '20281 Dexter Hill', '2837121655');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Calypso', 'Maura', 'Bischop', 'McGruar', '68643 Kinsman Drive', '6079266416');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Quill', 'Valle', 'Petters', 'Gange', '48 Elgar Drive', '4824373229');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Reinaldos', 'Stearne', 'Pirnie', 'Cowan', '34934 Quincy Terrace', '1857550578');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Tadeo', 'Gaston', 'Cawsy', 'Ridler', '4284 Sunnyside Junction', '1411467012');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Jamie', 'Philipa', 'Wenden', 'O''Kielt', '4542 Rowland Trail', '7642327774');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Germayne', 'Obadias', 'Trewartha', 'Giacobelli', '7729 Esch Drive', '6374862194');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Ina', 'Kaitlyn', 'McIlveen', 'Adams', '71608 Lillian Park', '5706989365');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Gwenny', 'Patti', 'Iacomettii', 'Pixton', '00654 Bluejay Road', '3038698056');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Emelia', 'Bartie', 'Breede', 'Hlavecek', '6451 Waubesa Crossing', '6601902283');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Cody', 'Lek', 'Krojn', 'Simoneton', '15879 Fieldstone Junction', '3548286020');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Missie', 'Jenelle', 'Saxton', 'Byfford', '1 Calypso Drive', '4119019020');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Krishnah', 'Hugo', 'Barford', 'Noonan', '5713 Duke Trail', '4109402681');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Olia', 'Wolfy', 'Churchman', 'Rupke', '73 Hallows Place', '8258049605');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Binni', 'Ogdon', 'Schneidar', 'Duberry', '7 Pine View Parkway', '1073402458');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Almire', 'Stanley', 'Suero', 'Corkett', '3 Hazelcrest Pass', '5766055104');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Abram', 'Dorie', 'Battrick', 'Ethersey', '050 Summer Ridge Lane', '1466779378');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Brunhilda', 'Frasier', 'Potebury', 'O''Brallaghan', '6567 Erie Alley', '6604133259');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Hannah', 'Joby', 'Guy', 'Bodycombe', '74 Warner Junction', '9341162199');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Hammad', 'Benoit', 'Dodd', 'Birkin', '50921 Badeau Park', '3832666238');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Paulita', 'Lou', 'Vescovo', 'Spiers', '7725 Vahlen Terrace', '1034358252');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Ann-marie', 'Idalina', 'Maddra', 'Polye', '9376 Arizona Plaza', '3797489410');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Renae', 'Fan', 'Babinski', 'Palffy', '217 Arapahoe Park', '5509039298');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Rafaelita', 'Myrvyn', 'Gash', 'Duplock', '8960 Harper Lane', '2356443194');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Mickie', 'Yolanda', 'Pyne', 'Treby', '7673 Jackson Way', '9192770109');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Fanchette', 'Tuesday', 'Lundbeck', 'Wanne', '949 Crowley Road', '7472833016');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Ailbert', 'Melly', 'Labern', 'Sellick', '4013 Haas Hill', '6297959187');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Merrill', 'Merralee', 'Ebbage', 'Rableau', '53693 Eagle Crest Drive', '7638729152');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Emmie', 'Hoebart', 'Lashmar', 'Summerson', '67 Dakota Trail', '1942199446');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Caresse', 'Andrej', 'Saward', 'Dalyell', '99979 Melody Point', '5777817518');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Yelena', 'Goddard', 'Hane', 'Roft', '32 Holmberg Junction', '5459597879');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Otho', 'Collette', 'Grummitt', 'Flay', '96811 Valley Edge Court', '6542682155');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Eugine', 'Jarred', 'Pearsall', 'Morrieson', '9 Vermont Street', '6641224168');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Cristine', 'Ilise', 'Peatman', 'Bravery', '76 Shasta Point', '9327132762');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Scottie', 'Tadd', 'Craggs', 'Peal', '58 Maywood Alley', '5944465995');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Thurstan', 'Katee', 'Leghorn', 'Loudwell', '98418 Fairfield Avenue', '7292657632');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Brodie', 'Nellie', 'Tsar', 'Russan', '0919 Surrey Terrace', '2126323976');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Pablo', 'Reggie', 'Morby', 'Creamen', '3 Norway Maple Circle', '3178511769');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Lotty', 'Isacco', 'Graysmark', 'Devereux', '82 Clove Way', '1619808094');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Mata', 'Clemente', 'Jado', 'Inglese', '245 Melby Court', '7162941387');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Doralin', 'Binni', 'Burch', 'Tawse', '7771 Sauthoff Center', '2004597598');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Roma', 'Wallace', 'Obee', 'Mackerness', '91 Debs Way', '9533592928');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Law', 'Freddy', 'Berzons', 'Dowker', '3911 Fairfield Parkway', '4202710244');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Florrie', 'Earl', 'Halloran', 'McGillreich', '81 Sloan Avenue', '1115092047');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Helenelizabeth', 'Madge', 'Grzesiewicz', 'Vinecombe', '7885 Colorado Terrace', '8459888496');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Janith', 'Kyle', 'Dannehl', 'Duly', '783 Clove Drive', '4366494324');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Fraze', 'Paule', 'Cannop', 'Novotna', '61348 Forster Way', '8894744107');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Helyn', 'Killie', 'Watkiss', 'Roads', '360 Menomonie Avenue', '5413723564');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Arlan', 'Raleigh', 'Malin', 'Hunnicot', '179 Continental Place', '5054451773');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Eliza', 'Camala', 'Jimpson', 'Traite', '55 Grayhawk Alley', '5207749687');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Debra', 'Den', 'Jewsbury', 'Bennet', '18302 Morningstar Avenue', '9225185612');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Fernando', 'Erena', 'Tresise', 'Roelvink', '94031 Sundown Circle', '8409206802');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Antonie', 'Durand', 'Jinks', 'Coad', '57010 Doe Crossing Trail', '5971259825');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Ricki', 'Chaim', 'MacParland', 'Coultar', '44738 Mcbride Circle', '8031370602');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Romain', 'Flint', 'Collar', 'Gainsford', '3372 Shasta Avenue', '3098336586');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Kelsey', 'Bridget', 'Yurikov', 'Lott', '32654 North Place', '9193365899');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Kathryne', 'Peggie', 'Pechard', 'Semorad', '590 Lawn Junction', '3968333247');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Roda', 'Olivero', 'Jumonet', 'Smithson', '84693 Bultman Plaza', '6275502062');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Abagail', 'Mort', 'Piser', 'Neave', '628 Coolidge Avenue', '1674698988');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Ara', 'Stafani', 'Farnes', 'Adamkiewicz', '1 Scofield Junction', '6876009759');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Gnni', 'Bobbie', 'Shillabeare', 'Bowskill', '1587 Oak Valley Park', '1713837369');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Gerri', 'Brose', 'Spoor', 'Silby', '7 Eastwood Avenue', '3948081432');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Mano', 'Ahmed', 'Grigorio', 'Addionizio', '10050 Park Meadow Center', '6423886604');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Amble', 'Pavel', 'Brandsma', 'Macilhench', '74 Heffernan Pass', '3736832535');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Elia', 'Lisa', 'Fewtrell', 'Wrenn', '64 Kennedy Alley', '8382019578');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Olly', 'Shela', 'Martinetto', 'Innot', '6 Gina Center', '6016461504');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Jaime', 'Vinnie', 'Have', 'Calwell', '222 Grim Avenue', '5185419570');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Rochell', 'Cammi', 'Liston', 'Bayman', '86288 Morningstar Parkway', '7432559734');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Emmy', 'Klaus', 'Silversmidt', 'Seres', '5 West Junction', '4725900555');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Diego', 'Terrie', 'Huckerby', 'Kernocke', '6961 Steensland Hill', '1192835988');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Pattin', 'Marlee', 'Blayney', 'Tiernan', '489 Brentwood Court', '9936219137');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Meggi', 'Rossy', 'D''Acth', 'Satch', '840 Crescent Oaks Point', '7978187317');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Bartlett', 'Asia', 'Chopy', 'Peasgood', '92 Lindbergh Parkway', '4616759356');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Killie', 'Lainey', 'Cassley', 'Dockray', '867 Warbler Plaza', '6816107446');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Pascal', 'Gabrila', 'Auld', 'Gatchel', '36611 Pepper Wood Terrace', '7965651278');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Anabel', 'Cheslie', 'Goforth', 'Methingam', '2 Northland Hill', '6083268010');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Kittie', 'Verine', 'Planque', 'Cumine', '594 Golf Course Pass', '5447714172');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Dion', 'Bobbe', 'Reedie', 'Redholls', '21224 Eagle Crest Place', '9427728745');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Zoe', 'Lindsey', 'Scirman', 'Whitelaw', '8 Oriole Road', '5113078578');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Angelita', 'Georgine', 'Culleton', 'Goslin', '974 Stang Junction', '8184429921');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Elka', 'Korey', 'Darragh', 'Kohtler', '103 Fallview Parkway', '6376950644');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Alicea', 'Morlee', 'Browncey', 'Comello', '57451 Pearson Plaza', '4705022357');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Michell', 'Clemente', 'Littleproud', 'Qualtro', '67651 Straubel Junction', '5815673992');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Leena', 'Jordan', 'Ellit', 'Willson', '35716 Blackbird Hill', '8264784829');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Carlin', 'Rikki', 'De Dantesie', 'Bransden', '6 Bartelt Park', '1561639137');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Magdalene', 'Maggy', 'Luney', 'Rubke', '919 Village Crossing', '1767332690');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Sari', 'Isidoro', 'Briamo', 'Swayton', '891 Charing Cross Plaza', '3524332628');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Jard', 'Hoyt', 'McFfaden', 'Twiggins', '2440 Straubel Court', '8243857919');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Rochette', 'Devin', 'Waghorn', 'Bedells', '29 Di Loreto Circle', '5275723130');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Antonius', 'Winnifred', 'Channon', 'Cappineer', '2447 Meadow Vale Center', '2627257844');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Jackson', 'Germain', 'Anstee', 'Saull', '845 Holy Cross Street', '8399693084');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Adelaide', 'Arvy', 'Tincey', 'Apthorpe', '39 Granby Terrace', '5836590856');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Osborn', 'Josee', 'Cettell', 'Bonnick', '18 Dapin Pass', '7504299553');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Lanie', 'Lance', 'Kernley', 'Silver', '6 Monica Crossing', '3277496345');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Hebert', 'Ralf', 'McCowen', 'Blincoe', '1 Manitowish Court', '8684082795');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Aretha', 'Katalin', 'Rubenczyk', 'Robley', '38 Oxford Pass', '3588636868');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Emmaline', 'Anselma', 'Clair', 'Johnston', '30076 Blackbird Center', '9742672571');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Rorke', 'Bili', 'Jowitt', 'MacAskie', '5 Anhalt Road', '5714654822');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Ricardo', 'Mellisa', 'Di Biagio', 'Geater', '48754 Independence Center', '7827252533');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Lon', 'Zachariah', 'Seear', 'Beyer', '7403 Ronald Regan Court', '5131700646');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Adrianna', 'Reinwald', 'Ganniclifft', 'Tattam', '928 Hauk Pass', '2615364133');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Broddie', 'Slade', 'Sandall', 'Ivison', '832 Orin Plaza', '7383549849');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Addie', 'Helene', 'Priestley', 'Foxen', '9 Eagle Crest Place', '6625626759');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Eadie', 'Marcille', 'Hazlewood', 'Emm', '14 Golf Hill', '1632530421');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Jervis', 'Elisabet', 'Riseborough', 'Inkster', '815 Reindahl Court', '1992040081');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Dora', 'Tye', 'Wrist', 'Gammel', '35 Shasta Alley', '5068721008');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Devlen', 'Wilt', 'Altham', 'Burgis', '7 Calypso Trail', '1576153758');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Tyson', 'Christa', 'McCrillis', 'Cuxson', '44 Helena Junction', '7681968547');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Mitzi', 'Ebba', 'Pepineaux', 'Brierley', '4 Eagle Crest Way', '4073792446');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Emmie', 'Hube', 'Fromont', 'Spring', '1 Holmberg Avenue', '1843873241');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Chickie', 'Lem', 'Douberday', 'Habbijam', '17453 3rd Terrace', '9557902833');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Taryn', 'Armando', 'Haddacks', 'Constantine', '04132 4th Street', '9296715222');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Teodor', 'Ardeen', 'Urlich', 'Moorman', '625 Farmco Junction', '8826199669');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Junette', 'Bradly', 'Mattiacci', 'Beinisch', '857 Bellgrove Hill', '9015128236');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Gweneth', 'Axe', 'Ledekker', 'Spreag', '2145 Lillian Drive', '4886472462');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Glen', 'Redford', 'Dunklee', 'Sheals', '2545 Leroy Court', '1061392670');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Amandi', 'Niki', 'Gergus', 'Whittek', '534 Darwin Drive', '8818890829');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Gail', 'Sawyer', 'Gabbatt', 'Physic', '13 Stephen Point', '9675298349');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Selle', 'Mordecai', 'Cortin', 'Foldes', '03 Village Road', '8509744004');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Ambros', 'Craggy', 'McTeer', 'Cogzell', '17725 Sauthoff Pass', '5038085968');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Leslie', 'Kyrstin', 'Offill', 'Acton', '2243 Schmedeman Park', '8598500770');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Jayne', 'Claudelle', 'Metzke', 'Sloyan', '21 Melrose Trail', '4817934307');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Claire', 'Gratiana', 'Meineken', 'Gilgryst', '61171 Oriole Place', '4119226913');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Melly', 'Elysee', 'Ewestace', 'Schohier', '9369 Mandrake Circle', '1297275008');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Maurizio', 'Gretal', 'Rosenbush', 'Durrand', '17 Autumn Leaf Way', '4977357428');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Buckie', 'Adelice', 'Thieme', 'Raiman', '25294 Northwestern Crossing', '8432239086');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Marwin', 'Tabatha', 'McGorman', 'Alu', '337 Miller Park', '8967168618');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Elle', 'Susana', 'Lockney', 'Gallie', '6557 West Way', '5378772540');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Oliviero', 'Christos', 'Tolworth', 'MacKellen', '600 Pepper Wood Center', '7829257436');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Denney', 'Elihu', 'Nicolls', 'Waterfield', '36 Old Shore Street', '7839576465');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Tiphani', 'Susana', 'Freire', 'Brakewell', '99 Evergreen Trail', '8806556182');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Skipper', 'Julieta', 'Arundel', 'Luttger', '77 Daystar Park', '9143929570');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Suzette', 'Mozes', 'Vannar', 'Full', '73 Bay Center', '2839298701');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Dew', 'Harriet', 'Miguel', 'Bantock', '6410 Spaight Trail', '8338906018');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Barry', 'Christel', 'Grise', 'Garrit', '18397 Prentice Alley', '3284386064');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Pepita', 'Shanan', 'Lamkin', 'Shillito', '3 Sachs Place', '5799292452');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Ferdinande', 'Gerianne', 'Gunny', 'Carthew', '8089 3rd Parkway', '5774785154');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Margarethe', 'Thayne', 'Benda', 'Gabler', '161 Steensland Alley', '9486984302');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Hadleigh', 'Melisande', 'Northern', 'Stefanovic', '24 Morning Way', '8263418985');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Consuela', 'Orson', 'Priddey', 'Youles', '2 Butterfield Point', '7266343497');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Rebeca', 'Billy', 'Epple', 'Tuffley', '1599 Carey Road', '6144144318');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Ulrica', 'Pat', 'Sivill', 'Pembry', '898 Thackeray Junction', '7526414477');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Claudia', 'Javier', 'Dignum', 'Spellward', '191 Ridgeview Avenue', '8775161018');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Lee', 'Thomasin', 'Mackro', 'Burnes', '5674 Duke Road', '2116214411');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Janek', 'Maye', 'Stuttard', 'Quinion', '919 Del Sol Circle', '9758984554');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Kip', 'Lewes', 'Pandie', 'Calf', '25 Acker Place', '7145984869');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Anneliese', 'Nichole', 'Bonn', 'Brunroth', '530 Talmadge Lane', '6177322359');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Coralyn', 'Bettye', 'Biddlestone', 'Tofful', '4 Caliangt Pass', '8046126628');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Nolie', 'Perri', 'Bevan', 'Lockwood', '749 Eliot Circle', '9035822228');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Halli', 'Caria', 'Slatford', 'Verman', '53 Oakridge Circle', '8045650319');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Tamqrah', 'Egon', 'Boag', 'Kneeshaw', '19 Grover Terrace', '1542802619');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Frieda', 'Garreth', 'Rodinger', 'McCawley', '2874 Mitchell Pass', '1157720448');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Hetti', 'Melina', 'Brokenbrow', 'Mallen', '630 Annamark Terrace', '4659976608');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Emlynn', 'Rosella', 'Leathers', 'De Domenici', '09 Dovetail Junction', '4271951546');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Kath', 'Cristen', 'Dinnage', 'Pickance', '42 Loomis Crossing', '4782540945');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Kristal', 'Dido', 'Ravenshaw', 'Gilroy', '10959 Nevada Point', '8299956344');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Marcelle', 'Eddy', 'Lamberts', 'Daborne', '9204 Prairieview Street', '4758530924');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Ludwig', 'Iggy', 'Goldhawk', 'Barme', '683 Magdeline Hill', '5861291397');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Hannah', 'Ahmed', 'Callicott', 'Boycott', '01 Clemons Avenue', '7245266378');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Marlyn', 'Danella', 'Perrington', 'Wattam', '85 Fordem Alley', '9476993710');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Maximilien', 'Di', 'Smitton', 'Aizikowitz', '8 Almo Road', '5822796623');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Evelin', 'Philipa', 'Whiteman', 'Nutbeam', '514 1st Pass', '7332207059');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Anetta', 'Kelwin', 'Donaho', 'Fairholme', '722 Lotheville Alley', '3461711719');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Marlyn', 'Fidelity', 'Twinberrow', 'Cotelard', '206 Trailsway Crossing', '2668271050');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Lynn', 'Pauly', 'Matherson', 'Masterton', '8 Goodland Junction', '7828436755');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Mart', 'Margi', 'Picott', 'Keyhoe', '5 Sutherland Place', '9883900224');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Hewie', 'Damien', 'De Freitas', 'Girod', '380 Comanche Hill', '9014001853');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Salem', 'Rebeca', 'Schrir', 'Venediktov', '7 Memorial Place', '5739697871');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Loy', 'Hector', 'Charpling', 'Prestland', '30679 Nobel Road', '9079835214');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Marketa', 'Flss', 'Dombrell', 'Exer', '38796 Parkside Parkway', '7753403877');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Karlis', 'Morry', 'Tapsell', 'Langhorne', '80 Prentice Alley', '2559596825');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Jewell', 'Randy', 'Spinello', 'Nand', '78889 Holy Cross Alley', '2392038486');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Miguelita', 'Parry', 'Jouhning', 'Byram', '1 Summer Ridge Pass', '9192549735');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Isiahi', 'Franciska', 'Cavolini', 'Rosenwald', '54 Everett Street', '2381306038');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Norine', 'Lexy', 'Harmon', 'Canwell', '1 Northwestern Point', '2353115886');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Georgianne', 'Annecorinne', 'Conley', 'Clewer', '2793 Sachtjen Court', '7103279439');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Kristien', 'Rachele', 'Renbold', 'Mulryan', '05741 Dayton Center', '8081009654');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Darrin', 'Dee', 'Quant', 'Troutbeck', '7687 Messerschmidt Place', '2469663265');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Giavani', 'Bertram', 'Danilyak', 'Taveriner', '3 Little Fleur Circle', '1752705212');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Jayme', 'Griff', 'Ambrose', 'Bowmaker', '6703 Montana Avenue', '9506776654');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Sissy', 'Demetris', 'Message', 'Filson', '07442 Manufacturers Terrace', '6242361844');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Erl', 'Valdemar', 'Corfield', 'Longrigg', '7846 Clyde Gallagher Road', '5297992681');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Frederica', 'Hally', 'Olley', 'O''Scanlon', '79 Troy Plaza', '8808708060');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Blake', 'Elita', 'Tattershaw', 'Stare', '3673 Holy Cross Road', '8114908048');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Berna', 'Zita', 'Smalles', 'Gavey', '517 Mockingbird Drive', '9896710636');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Chip', 'Hazel', 'Abisetti', 'Backwell', '6750 Service Street', '5995828556');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Sebastien', 'Harmonia', 'Alkin', 'Tirkin', '95 Esch Avenue', '2621711711');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Yetta', 'Manuel', 'Margrem', 'Giorgiutti', '696 Dayton Avenue', '8772050814');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Larisa', 'Arliene', 'Kestian', 'Inglefield', '9167 Fairview Road', '8846409579');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Cahra', 'Aloise', 'Duncombe', 'Patriche', '86 Ronald Regan Pass', '4843974069');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Billy', 'Viki', 'Mortel', 'Oxtoby', '9 Reinke Hill', '4569703239');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Lorri', 'Andrey', 'Provis', 'Kaubisch', '7 Roxbury Alley', '9279084477');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Irvine', 'Care', 'Look', 'Morgen', '1 Spohn Hill', '4671703944');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Lettie', 'Sophie', 'McAlees', 'Coat', '3980 Rockefeller Trail', '3876687381');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Orazio', 'Nanon', 'Poter', 'Pitman', '93 Sommers Junction', '9087202218');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Roderich', 'Eachelle', 'Aiton', 'Blundan', '97 Duke Hill', '2722456284');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Melania', 'Giorgia', 'Franciottoi', 'Ovell', '9351 Anniversary Crossing', '7608453270');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Padraig', 'Shelbi', 'Fawdrey', 'Kelcey', '7575 Fremont Drive', '4208618959');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Matthew', 'Casi', 'Hedworth', 'Grishakov', '82 Melody Way', '4476302344');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Ulric', 'Fran', 'McClunaghan', 'Swiffan', '11751 Ronald Regan Place', '2234127857');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Sarine', 'Antin', 'Daymont', 'Raft', '2 5th Way', '9921298047');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Melanie', 'Haywood', 'Tomalin', 'Petley', '89 Nobel Court', '7711197337');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Gleda', 'Mirelle', 'Bonder', 'Junkison', '650 Little Fleur Street', '9176372230');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Sharia', 'Felizio', 'Cush', 'Mascall', '21035 Eagle Crest Pass', '2235260380');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Leah', 'Gayleen', 'Greenless', 'Halvosen', '5385 Sachtjen Parkway', '8281735254');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Audrey', 'Tybi', 'Aylwin', 'Stovold', '8081 Paget Street', '9311762396');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Theressa', 'Jory', 'Havard', 'Barker', '15931 American Plaza', '9488637866');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Emiline', 'Karin', 'Livett', 'Loudwell', '550 Hovde Pass', '6938347145');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Latia', 'Lucie', 'Cathrall', 'Suarez', '6552 Arkansas Crossing', '6214335448');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Myriam', 'Torrie', 'Hollingsby', 'Lovstrom', '90 Mesta Street', '5188369298');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Wilfrid', 'Atlanta', 'McGahey', 'Burne', '40256 Brickson Park Park', '2085242186');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Penelope', 'Mikel', 'Gartland', 'D''Alessandro', '8 Hazelcrest Parkway', '8507768439');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Casey', 'Gusty', 'Pele', 'Orsman', '67204 Hintze Lane', '3573268024');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Julia', 'Izabel', 'Townend', 'Nuemann', '351 Jay Crossing', '3308677709');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Gilberto', 'Derek', 'Pinkard', 'Barlass', '3 Twin Pines Junction', '1477213608');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Aurthur', 'Jecho', 'Hannaway', 'Gorse', '3 Forest Drive', '1901457166');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Desmond', 'Luci', 'Dumphrey', 'Elion', '6238 Brown Plaza', '1493755487');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Traver', 'Bogey', 'Greenan', 'Swindells', '52097 Prairie Rose Court', '7662498723');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Ivonne', 'Jae', 'Laybourn', 'Monck', '929 Roxbury Street', '9616593239');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Daune', 'Francoise', 'Cowser', 'Putman', '2 Glendale Junction', '4292363548');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Romola', 'Traver', 'Jeannin', 'Feaks', '938 Jenifer Hill', '1464805047');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Fredra', 'Georas', 'Bessell', 'Bosward', '68 Acker Place', '7526993079');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Deina', 'Benny', 'Feathers', 'Riping', '7 Bashford Terrace', '8438977483');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Matti', 'Alexandros', 'Carrigan', 'McPaike', '68217 Merry Point', '1651617870');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Marijo', 'Kathleen', 'Tollit', 'Clapston', '64 Ridge Oak Pass', '5129967807');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Quill', 'Emeline', 'Marton', 'Pietrzyk', '4 Bluejay Court', '1288943006');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Daisie', 'Salomon', 'Walkey', 'Munden', '29 Acker Alley', '6829935984');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Miner', 'Damian', 'Devitt', 'Rosenfelt', '0452 Ridgeway Parkway', '6609263207');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Meredeth', 'Bunny', 'Brawn', 'Tombleson', '5503 Huxley Junction', '4192513572');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Arlyn', 'Chad', 'Brambill', 'Philliskirk', '06844 Loftsgordon Crossing', '6142454576');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Jackelyn', 'Carlie', 'Dix', 'Edgeller', '88595 Rigney Way', '3425391621');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Herbert', 'Waiter', 'Scouler', 'Syrie', '05 Rutledge Place', '7925062614');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Flossie', 'Kelli', 'Huggard', 'Fried', '0734 Westridge Hill', '8516241713');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Cy', 'Daisey', 'Caskie', 'Clemenson', '543 Superior Crossing', '9595949294');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Ingmar', 'Stacy', 'Scotchmoor', 'Sulman', '41 Farragut Hill', '3506000788');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Simmonds', 'Lalo', 'Lorkin', 'Bewshea', '9 Marquette Junction', '2648550395');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Gary', 'Maggee', 'Regi', 'Corley', '7 Huxley Plaza', '6291226028');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Bealle', 'Fernande', 'Delepine', 'Salerg', '3643 Elgar Way', '4735570131');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Harry', 'Violante', 'Kalinsky', 'Rosenblath', '6057 Brown Trail', '9604065702');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Lek', 'Skell', 'Baysting', 'Roj', '438 Cordelia Plaza', '6744184393');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Daphene', 'Wylma', 'Jarred', 'Sackler', '37401 5th Point', '3973541099');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Ailene', 'Cosette', 'Eusden', 'Leatherbarrow', '91 Lien Court', '1375620163');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Benton', 'Marne', 'Rude', 'Noorwood', '06476 Memorial Way', '2854954221');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Mirabella', 'Laverna', 'Maybery', 'Pavlovic', '76183 Hoffman Court', '7821356945');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Simone', 'Daphene', 'Bomfield', 'Copsey', '11 Coleman Alley', '1663460409');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Dukey', 'Artair', 'Valencia', 'Whaites', '295 Sage Alley', '9615116783');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Zonnya', 'Queenie', 'Comiskey', 'Arnoult', '0830 Vernon Drive', '8394400414');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Ruben', 'Riley', 'Dowe', 'Kennerknecht', '286 Colorado Hill', '4877236757');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Mickey', 'Isacco', 'Ortner', 'Drewitt', '22 Northwestern Way', '4559815189');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Richard', 'Cynthy', 'Skehens', 'Davidy', '7 Commercial Trail', '9371106837');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Stirling', 'Alwin', 'Drake', 'Poon', '4 Kropf Road', '5156367786');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Coriss', 'Johnette', 'Evans', 'Girardy', '944 Katie Pass', '3363773601');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Gram', 'Ogden', 'Barwick', 'Wreford', '3860 Larry Park', '4137718050');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Anselma', 'Marris', 'Foulks', 'Faulkner', '534 Springs Hill', '9778889937');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Aloise', 'Dael', 'Bravington', 'Loud', '41376 Scoville Alley', '1812418043');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Daisy', 'Zsazsa', 'Chatin', 'Kingshott', '40290 Scoville Point', '1735192058');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Dario', 'Babara', 'Gutridge', 'Carnachen', '607 Summit Junction', '4688319342');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Peri', 'Retha', 'Goodspeed', 'Baish', '9785 Eastwood Junction', '4552609304');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Alano', 'Lin', 'Hacker', 'Durran', '722 Anderson Junction', '9708127006');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Reiko', 'Henrie', 'Ibbott', 'Rosander', '48 Hanover Way', '2102559217');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Ogdon', 'Elsy', 'McEnteggart', 'Tremberth', '189 Dawn Place', '3865117421');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Mignonne', 'Adam', 'Sievewright', 'Pordall', '480 Hoffman Place', '6257642502');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Russ', 'Hyatt', 'Grancher', 'Novotni', '03183 Westport Avenue', '2024433313');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Theodosia', 'Dimitri', 'Dryden', 'Sinnocke', '3933 Dakota Alley', '2632543027');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Chicky', 'Laughton', 'Guiden', 'Picardo', '63 Bluejay Parkway', '9731142893');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Rolland', 'Amii', 'Kidd', 'Grunwall', '1433 Talmadge Park', '4206762411');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Fair', 'Melba', 'Keohane', 'Cowerd', '63580 Cascade Drive', '6333771669');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Savina', 'Helsa', 'Ash', 'Bagley', '487 Monterey Place', '4043051504');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Annabelle', 'Shawna', 'Claybourn', 'Ingold', '59544 Armistice Trail', '9721507636');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Carney', 'Rorke', 'Purslow', 'Henfre', '60775 Waubesa Center', '2778770001');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Wynne', 'Melisandra', 'Klehn', 'Gerding', '4 Spohn Road', '2216865787');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Aidan', 'Wendy', 'Cheales', 'Fennick', '75 Michigan Point', '6848185988');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Maible', 'Kleon', 'Puttan', 'Odlin', '38719 Amoth Parkway', '5863178014');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Lilla', 'Claribel', 'Foggo', 'Brouwer', '277 Nelson Lane', '9807132618');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Des', 'Talia', 'Carillo', 'Boyne', '02 Scoville Plaza', '8328191605');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Delores', 'Tadd', 'Saggs', 'Beuscher', '801 Nevada Lane', '5547148471');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Korney', 'Fanchette', 'Brangan', 'Ellwell', '0 Bay Parkway', '5201565815');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Vito', 'Kacie', 'Kyberd', 'Sabben', '6 Gale Terrace', '2814046447');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Lynelle', 'Lewiss', 'Garrison', 'Huerta', '910 Pennsylvania Place', '4041924030');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Mollee', 'Heda', 'McCaughey', 'Tebboth', '1 Charing Cross Terrace', '5963088693');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Obed', 'Issy', 'Haggish', 'Livoir', '9625 Sloan Lane', '8357886062');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Essy', 'Torey', 'Norrington', 'Langfat', '1190 Ruskin Avenue', '9295398905');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Claudina', 'Frazer', 'Edworthye', 'Backhouse', '406 Swallow Hill', '8586114985');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Leland', 'Fulton', 'Tomaini', 'O''Finan', '18241 Fallview Street', '3871998473');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Tally', 'Rozina', 'Labden', 'Wickwarth', '65728 Sommers Road', '7549352065');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Caralie', 'Vassili', 'Kitchingman', 'Dmiterko', '99 Meadow Ridge Junction', '1574839538');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Shelagh', 'Rosaleen', 'Crosier', 'Sidsaff', '9 Nevada Park', '4429764720');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Cecilius', 'Ludovico', 'Attack', 'Brunetti', '68876 Jenifer Way', '7337650607');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Kayley', 'Karl', 'Achrameev', 'Pattison', '3239 Canary Road', '7663438376');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Land', 'Giulia', 'Blundin', 'Garric', '07483 Butterfield Drive', '7582927818');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Zarah', 'Lacie', 'Suttaby', 'Reveland', '0 Grayhawk Terrace', '3029203230');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Tyrone', 'Mozes', 'Armsby', 'Attoe', '4797 Shelley Drive', '7875792792');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Cyndi', 'Lorrayne', 'McGaw', 'Molian', '02233 Declaration Court', '5294927232');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Hill', 'Cacilie', 'Aburrow', 'Panswick', '542 Sutteridge Trail', '4108934927');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Mathias', 'Carlita', 'Stidever', 'Eskriet', '9806 Fisk Pass', '8288172905');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Ranice', 'Brandice', 'Alliband', 'Lambourne', '68443 Crest Line Point', '8418691625');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Carolynn', 'Maxie', 'Hardwell', 'Poxon', '24793 Manitowish Crossing', '8135139005');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Brigid', 'Koo', 'Cluet', 'Grabeham', '5 2nd Avenue', '1272341518');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Anselm', 'Marleah', 'Amos', 'Crosfield', '5 Rockefeller Alley', '4196932899');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Alida', 'Arlee', 'Delyth', 'Benediktovich', '7182 Troy Road', '8496849595');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Emiline', 'Arv', 'Ebbin', 'Hartless', '32115 Pleasure Avenue', '3039533248');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Harwell', 'Jeannette', 'Kelf', 'Recher', '37 Harper Hill', '6731350151');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Barbara-anne', 'Wolfgang', 'Kivlin', 'Tribe', '38 Utah Plaza', '3696856739');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Freddie', 'Diana', 'Donnellan', 'Hardwidge', '473 Sommers Drive', '2138663354');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Tamar', 'Raimund', 'Bazoge', 'Provest', '8 Miller Parkway', '9352920612');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Aguste', 'Tomas', 'Veregan', 'Goring', '0275 Barnett Center', '1933641454');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Yvor', 'Shannon', 'Doran', 'Alcoran', '86658 Havey Court', '2763069412');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Junette', 'Pancho', 'Wayland', 'Blonfield', '78 Warrior Plaza', '5098271585');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Holmes', 'Benita', 'Olding', 'Engel', '69023 Grim Center', '4313625286');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Davon', 'Sandra', 'Birkhead', 'Dallicoat', '6876 Larry Pass', '4029581543');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Jorey', 'Brandice', 'Girault', 'Hawkeridge', '9 American Ash Center', '3925487911');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Ilysa', 'Silva', 'Bleasdale', 'MacNeilage', '53455 Rigney Pass', '7868705649');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Ulysses', 'Mickey', 'Diamond', 'Benardette', '83 Pankratz Terrace', '8399742211');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Karoly', 'Giacomo', 'Kennaird', 'Dank', '28488 Nelson Drive', '2607466155');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Phyllis', 'Helen', 'Swede', 'Mila', '58 Hansons Point', '5727336898');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Caz', 'Ase', 'Traves', 'Ogley', '1 Dryden Court', '8413719933');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Onfroi', 'Karoly', 'Twohig', 'Brave', '33730 Lakewood Gardens Park', '2424379189');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Francis', 'Aldus', 'Merigeau', 'Atthow', '32 Ridgeview Alley', '4979139030');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Francisca', 'Larine', 'Wrathmall', 'Kasher', '5805 Mccormick Hill', '9985092917');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Clarie', 'Elmore', 'Sheepy', 'Worg', '843 Kingsford Circle', '7294381000');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Thibaut', 'Dino', 'Colebourn', 'Brockbank', '71 Holmberg Place', '3516293961');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Wood', 'Theodosia', 'Scrivinor', 'Nisbet', '26365 Jana Junction', '4538714260');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Dianemarie', 'Debbi', 'Hembling', 'Andrasch', '788 Merchant Junction', '5853685484');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Kati', 'Karina', 'MacMakin', 'Lippini', '51204 Mandrake Court', '1654866420');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Yuma', 'Chryste', 'Tejada', 'Hanby', '9 Corscot Trail', '7368945321');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Christos', 'Armin', 'Ferro', 'Halfhyde', '07 Sunnyside Park', '1641400027');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Kaycee', 'Sergent', 'Mordie', 'Burtwhistle', '59740 Lyons Terrace', '8839978964');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Barton', 'Connie', 'Belz', 'Revens', '58673 Mockingbird Circle', '8489871991');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Nollie', 'Libby', 'O'' Hanvey', 'Perrot', '67810 Sunnyside Place', '9495830155');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Marylou', 'Calley', 'Ciccoloi', 'Rappaport', '95 Stoughton Park', '8687999654');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Reinald', 'Daisie', 'Chasle', 'Hayers', '509 Warbler Road', '5002869000');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Karoly', 'Eada', 'Oakland', 'Tims', '425 Golden Leaf Point', '7065263415');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Esmaria', 'Brigit', 'Smedmore', 'Leffek', '76 Buhler Pass', '8354083468');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Pru', 'Reg', 'Pippin', 'Gudeman', '255 Barnett Plaza', '4381295539');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Libby', 'Riobard', 'Godlee', 'Magrannell', '3 Laurel Hill', '9562157911');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Salomi', 'Jerrold', 'Filer', 'Fruish', '661 Bultman Junction', '7714630338');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Eleonora', 'Erin', 'Keaveney', 'Muris', '83123 Kim Terrace', '2581298444');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Deloris', 'Gisele', 'MacKinnon', 'Ridpath', '67 David Drive', '3754542030');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Conroy', 'Nonah', 'Hoyte', 'Malsher', '4 Oakridge Street', '7438886364');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Franciskus', 'Pete', 'Fery', 'Vickarman', '652 Northwestern Park', '6432967027');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Quincy', 'Natalie', 'Gouthier', 'Casse', '1 Bonner Hill', '8609841086');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Catharine', 'Filberto', 'Duffree', 'West-Frimley', '2 Northfield Lane', '1598110398');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Georgianna', 'Tobe', 'Harpur', 'Blewitt', '68 Blackbird Place', '9869877486');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Marysa', 'Marylee', 'McAdam', 'Newnham', '5604 Hermina Court', '8946696396');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Sarena', 'Cosme', 'Feldmark', 'Finlayson', '85160 Butterfield Terrace', '3457992795');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Zachery', 'Nichol', 'Boddymead', 'Stollery', '0105 New Castle Crossing', '2295805426');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Job', 'Reinold', 'Mines', 'Crottagh', '33782 Logan Park', '6504974752');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Estele', 'Bryn', 'Tofful', 'Shergill', '7 Coleman Park', '5678388526');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Serena', 'Wildon', 'Jopp', 'Amthor', '40 Glacier Hill Court', '7293989314');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Chandal', 'Doloritas', 'Corrin', 'Eslemont', '674 Melody Avenue', '9636617302');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Editha', 'Nikolia', 'Troyes', 'Backshill', '4004 Lyons Parkway', '7935693973');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Dud', 'Elvera', 'Fahrenbacher', 'Shildrake', '7182 Scoville Avenue', '1247992501');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Alvera', 'Angel', 'Boylan', 'Cronk', '14896 4th Circle', '6097099489');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Barr', 'Kate', 'Meekins', 'Dongate', '5345 Farragut Junction', '5046796295');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Dani', 'Keefe', 'Geany', 'Trowbridge', '802 Hintze Parkway', '6073145171');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Franzen', 'Tiff', 'Drayson', 'Casterton', '10397 Gulseth Parkway', '9463401156');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Jamison', 'Simona', 'Aspinell', 'Yuranovev', '7 Porter Plaza', '7739306851');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Murry', 'Britta', 'Pie', 'Theml', '4 Kim Pass', '3822093012');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Emilee', 'Augustina', 'Rulton', 'Lafond', '87 Caliangt Parkway', '9902184051');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Reilly', 'Nelly', 'Cannell', 'Knock', '1 Iowa Alley', '5296258277');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Monique', 'Veronica', 'Bakster', 'Rosenfield', '1 Corry Hill', '4405388618');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Maritsa', 'Wake', 'Charte', 'Lowers', '8 Lakewood Center', '5262672792');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Dione', 'Merrielle', 'Rosenwald', 'Teodoro', '5 Goodland Crossing', '4075325347');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Gradey', 'Ricki', 'Merrell', 'Tembey', '4 Maryland Drive', '7239870946');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Irvine', 'Dino', 'Sedgwick', 'Sorrel', '78 Talisman Alley', '8576381099');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Spike', 'Allyson', 'Yandell', 'Grinley', '4 Knutson Junction', '7756108831');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Herb', 'Neil', 'Sambeck', 'Belfit', '2 American Place', '5277332032');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Verina', 'Duky', 'Jira', 'Philler', '0544 Fair Oaks Pass', '1117967071');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Mikel', 'Danielle', 'Bessett', 'Hofler', '85 Fordem Place', '5061728685');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Spense', 'Lavinia', 'Staneland', 'Ginglell', '3 Golden Leaf Terrace', '5953871464');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Marshal', 'Nikki', 'Northall', 'Cootes', '5 Transport Pass', '3904627986');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Dniren', 'Dayna', 'Behrendsen', 'Burlingame', '47 Dexter Avenue', '3335606022');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Rubin', 'Nicol', 'Diwell', 'Fortesquieu', '18 Cody Point', '5706944405');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Konstantine', 'Alvin', 'McCall', 'Georghiou', '24 Ridgeview Plaza', '7654263703');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Enrichetta', 'Antony', 'Casford', 'McTeer', '76028 Maryland Alley', '2032318143');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Anna-diane', 'Frasco', 'Llorens', 'McNish', '087 Hermina Road', '1184176407');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Karlie', 'Addison', 'Rippen', 'Petrowsky', '18678 Dakota Hill', '1952911697');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Caleb', 'Randie', 'Matula', 'Mc Grath', '1 Sloan Trail', '1109641438');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Margalit', 'Hercule', 'South', 'De Bischop', '619 Springs Drive', '8094224101');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Poppy', 'Zsazsa', 'Haythorne', 'Myers', '8 Cherokee Parkway', '2955173005');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Zahara', 'Sal', 'Vasechkin', 'Faichney', '0 Debra Place', '8406655460');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Ferguson', 'Asia', 'Fincken', 'Cafferty', '9576 2nd Place', '1541999739');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Arron', 'Mildrid', 'Weatherill', 'Buckles', '92 Carioca Pass', '9825273153');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Fredia', 'Rozella', 'Glasbey', 'Bein', '3017 Bashford Circle', '5864148955');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Alameda', 'Ram', 'Pidgeon', 'Colquhoun', '98202 Rieder Avenue', '4062401956');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Igor', 'Nikos', 'Anwell', 'Dyble', '5644 Morrow Point', '3543697388');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Francine', 'Dianemarie', 'Kinnar', 'Bastie', '7181 Columbus Crossing', '9772301746');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Jenna', 'Adelheid', 'Pagram', 'Camplejohn', '29796 Shasta Park', '1855634944');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Fin', 'Audrye', 'De Angelo', 'Beckhurst', '6 Golf Pass', '8786330508');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Herman', 'Randy', 'Mordey', 'Veque', '26 Packers Lane', '3506238994');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Weber', 'Kamila', 'Goranov', 'Jorden', '0215 Kropf Avenue', '6557637042');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Worthington', 'Berna', 'Waud', 'Bodicum', '30695 Toban Circle', '3278127143');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Maurise', 'Olimpia', 'Rodgier', 'Huccaby', '2074 Heath Alley', '6755603320');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Hans', 'Riannon', 'MacCostye', 'Titherington', '771 Killdeer Road', '5936070275');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Renell', 'Juan', 'Luparti', 'Albury', '939 Corben Hill', '1863344258');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Fanchon', 'Curr', 'Gilham', 'Birks', '4 Sunfield Circle', '4727729973');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Amos', 'Dulcie', 'McGrory', 'O''Bradden', '2168 Vernon Center', '4577340955');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Doralin', 'Ev', 'Sells', 'Dunbar', '4 Delladonna Center', '5108985969');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Jacklyn', 'Rod', 'Scrancher', 'Korneev', '798 La Follette Junction', '3022178453');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Avrom', 'Bren', 'Pembry', 'Jellis', '42 Gulseth Point', '5017580099');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Steffen', 'Kari', 'Iddenden', 'Chasier', '225 Eliot Alley', '4507687935');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Clementine', 'Kiele', 'Atterbury', 'Norman', '85781 Corben Road', '5369917548');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Katti', 'Bradan', 'McKellar', 'Shury', '93 Chive Hill', '4188074343');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Barbabra', 'Charo', 'Glavis', 'Catley', '5 Spenser Hill', '6301263934');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Basilio', 'Selene', 'Sandison', 'Taft', '022 Eagan Crossing', '8295382099');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Gordan', 'Mike', 'Oluwatoyin', 'Snaith', '04503 Commercial Street', '4502805808');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Cherie', 'Joelie', 'Batie', 'Lush', '26 Dayton Road', '3388999254');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Iorgos', 'Benson', 'Mabb', 'Geffen', '379 Declaration Trail', '2047828463');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Bryn', 'Lorie', 'McKag', 'Pawlyn', '2800 Blackbird Drive', '1507420142');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Imojean', 'Falito', 'Michieli', 'Busch', '68002 Leroy Parkway', '9528137892');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Gayle', 'Romain', 'Tilbrook', 'Gerlts', '84872 Knutson Junction', '4819492223');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Cullie', 'Harriett', 'Monday', 'Pendreigh', '32 Lerdahl Lane', '7678198423');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Inez', 'Ulises', 'Geekie', 'Janousek', '19 Hintze Alley', '6385132333');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Peterus', 'Irvin', 'Warrillow', 'Pauletti', '4706 Almo Avenue', '4601714848');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Dara', 'Joice', 'Cakes', 'Bollen', '32103 Corry Crossing', '4316372289');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Tamqrah', 'Vera', 'Bann', 'Blowing', '2 Rigney Hill', '9862404173');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Skell', 'Hyacinthia', 'Willers', 'Bickerstasse', '9903 David Hill', '6653131322');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Vinson', 'Flossie', 'Windrum', 'Flagg', '85 Mcbride Trail', '4978209664');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Norrie', 'Gasparo', 'Wagenen', 'Abazi', '0203 Buena Vista Parkway', '7078900786');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Toinette', 'Colas', 'Chisnall', 'Acosta', '2856 Hovde Point', '3797524299');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Sandie', 'Dylan', 'Scarasbrick', 'Knutton', '1 Ludington Point', '8105306310');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Elisa', 'Lock', 'Crosgrove', 'Vaune', '0488 Almo Park', '8344633679');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Heda', 'Christos', 'Sweed', 'Ellerker', '67570 Blackbird Center', '6964285147');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Catherine', 'Colet', 'Novic', 'Lovelace', '40 Marcy Point', '3704306137');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Ellary', 'Jesus', 'Starmer', 'Bizley', '6 Browning Hill', '2076480453');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Malynda', 'Eugenia', 'Benediktsson', 'Lathom', '09 Delladonna Pass', '9715947099');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Raffaello', 'Dione', 'Afonso', 'Grodden', '177 American Pass', '7202927588');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Belvia', 'Dosi', 'Frugier', 'Lapthorne', '4 Main Street', '3205707560');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Carmella', 'Andris', 'Swendell', 'O''Quin', '880 Brickson Park Junction', '9415538263');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Katuscha', 'Monica', 'Mebs', 'Woodrup', '780 Carpenter Court', '1378924604');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Korie', 'Lusa', 'Van Oort', 'Binden', '2379 Roth Center', '8178501402');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Tommie', 'Robb', 'De Moreno', 'Pendlebery', '1 Ruskin Park', '1222421624');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Marlo', 'Tyson', 'Cavendish', 'Kroch', '5 Harbort Trail', '6105289038');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Vanny', 'Ado', 'Banfield', 'Tschursch', '7155 Lerdahl Drive', '6387274855');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Ida', 'Carree', 'Uman', 'Adamski', '85070 Dottie Road', '6233264265');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Manolo', 'Tony', 'Poxson', 'Origin', '89 Towne Plaza', '5071418405');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Jorge', 'Lisette', 'Strood', 'Donohue', '846 Almo Street', '1171797944');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Elita', 'Martynne', 'Silby', 'Pirri', '05185 Fairfield Center', '2559244580');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Joshua', 'Freddy', 'Wimbush', 'Vertigan', '0561 Orin Place', '9728029443');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Arlee', 'Marlo', 'Gland', 'Westrip', '33177 Loomis Terrace', '5327735693');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Rosemaria', 'Udell', 'Moffatt', 'Emanueli', '79661 Helena Parkway', '2519009055');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Bond', 'Lyman', 'Hawksley', 'McAlister', '0817 3rd Court', '3738453390');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Karoly', 'Dunn', 'Boscott', 'Meah', '8 Rieder Alley', '8121041467');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Beniamino', 'Egan', 'Oxe', 'Limpenny', '4 Lerdahl Pass', '9274352682');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Rene', 'Bard', 'Moncrieffe', 'Sidry', '6 Weeping Birch Circle', '4356332792');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Stacee', 'Aile', 'Lebrun', 'Acreman', '42 East Way', '9862798646');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Thorvald', 'Lin', 'Spuner', 'Dinning', '76 Stuart Way', '9532374554');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Derron', 'Aloysia', 'Wayte', 'Sallans', '58 Canary Drive', '7478671457');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Collin', 'Gabbie', 'Boame', 'Lawday', '1 Onsgard Place', '5877666003');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Casey', 'Demott', 'Wines', 'Van', '87 Continental Hill', '1705343837');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Rene', 'Thaine', 'O''Fielly', 'Aleksandrikin', '18 Ramsey Alley', '7118020428');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Sammy', 'Lucila', 'Treverton', 'Rusbridge', '62 Dixon Circle', '4019616196');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Betty', 'Sophi', 'Jovasevic', 'Ware', '2896 Hansons Street', '6022455309');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Tiebout', 'Gorden', 'Spalding', 'Trustie', '591 Thompson Parkway', '8045035311');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Georgia', 'Melva', 'Stavers', 'Coners', '90686 Quincy Lane', '6355307698');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Angy', 'Tedd', 'Gosnall', 'Dourin', '7962 Larry Street', '6816515052');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Juanita', 'Rodd', 'Biesterfeld', 'Gosnell', '4 Stuart Street', '7867468917');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Nikolia', 'Taddeusz', 'Nash', 'Sherratt', '630 Saint Paul Junction', '8066296636');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Terri', 'Ferrel', 'Sex', 'Paddemore', '26448 Beilfuss Place', '7948812410');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Cyndy', 'Roanna', 'Shaefer', 'Punchard', '8635 Darwin Alley', '3854962337');
insert into Clientes (PNCliente, SNCliente, PACliente, SACliente, DirC, TelCliente) values ('Price', 'Zed', 'Verdun', 'Dunlop', '82 Namekagon Hill', '5507332917');
